### ISSUE TITLE
Update linters.yaml to run linting on PRs and push to main

### ISSUE THREAD

**Issue by jcadam14** [cfpb/regtech-data-validator#324]
Need to update the linters.yaml with the following:
```
on:
  pull_request:
  push:
    branches:
      - "main"
```
